SET BASEDIR=%~dp0..
SET BASEDIR=%BASEDIR:\bin\..=%

SET SERVER_CONFIG=%BASEDIR%\etc\server.cfg
SET CLIENT_CONFIG=%BASEDIR%\etc\client.cfg

SET PATH=%BASEDIR%\bin;%PATH%

SET RUBYLIB=%BASEDIR%\lib;%RUBYLIB%
SET RUBYLIB=%RUBYLIB:\=/%
